# Generated by Django 3.0.4 on 2020-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=251)),
                ('flag', models.CharField(max_length=251)),
                ('reports', models.CharField(max_length=251)),
                ('cases', models.CharField(max_length=251)),
                ('deaths', models.CharField(max_length=251)),
                ('recovered', models.CharField(max_length=251)),
                ('lat', models.CharField(max_length=251)),
                ('lng', models.CharField(max_length=251)),
                ('deltaCases', models.CharField(max_length=251)),
                ('deltaDeaths', models.CharField(max_length=251)),
            ],
        ),
    ]
