# Generated by Django 3.0.4 on 2020-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200330_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
